##### Building a Neural Network from Scratch: Implement feedforward and backpropagation in NumPy

In [1]:
import numpy as np

In [2]:
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [3]:
print(X.shape)
print(y.shape)

(4, 2)
(4, 1)


In [4]:
W1 = np.random.rand(2,2)

print(W1)

[[0.90990311 0.25573762]
 [0.88435478 0.11400726]]


In [5]:
b1 = np.random.rand(1,2)

print(b1)

[[0.40372856 0.62493194]]


In [6]:
x = X[0]

print(x)

[0 0]


In [9]:
z1 = np.dot(x, W1) + b1

print(z)

[[0.40372856 0.62493194]]


In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [11]:
a1 = sigmoid(z1)

In [12]:
W2 = np.random.rand(2,1)
b2 = np.random.rand(1,1)

In [13]:
z2 = np.dot(a1, W2) + b2

In [14]:
a2 = sigmoid(z2)

In [15]:
z1 = np.dot(X, W1) + b1
a1 = sigmoid(z1)

z2 = np.dot(a1, W2) + b2
a2 = sigmoid(z2)

In [16]:
loss = np.mean((y - a2) ** 2)

print(loss)

0.3238730495268777


In [17]:
error = y - a2

In [18]:
a = sigmoid(x)

In [19]:
def sigmoid_derivative(a):
    return a * (1 - a)

In [20]:
delta2 = (a2 - y) * sigmoid_derivative(a2)

In [21]:
dW2 = np.dot(a1.T, delta2)

In [22]:
db2 = np.sum(delta2, axis=0, keepdims=True)

In [23]:
delta1 = np.dot(delta2, W2.T) * sigmoid_derivative(a1)

In [24]:
dW1 = np.dot(X.T, delta1)

db1 = np.sum(delta1, axis=0, keepdims=True)

In [25]:
learning_rate = 0.1

In [26]:
W2 -= learning_rate * dW2
b2 -= learning_rate * db2

W1 -= learning_rate * dW1
b1 -= learning_rate * db1

In [27]:
for epoch in range(10000):

    # Feedforward

    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Loss

    loss = np.mean((y - a2) ** 2)

    # Backpropagation

    delta2 = (a2 - y) * sigmoid_derivative(a2)

    dW2 = np.dot(a1.T, delta2)
    db2 = np.sum(delta2, axis=0, keepdims=True)

    delta1 = np.dot(delta2, W2.T) * sigmoid_derivative(a1)

    dW1 = np.dot(X.T, delta1)
    db1 = np.sum(delta1, axis=0, keepdims=True)

    # Update

    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

In [28]:
print(a2)

[[0.05413915]
 [0.95067065]
 [0.95080694]
 [0.05292452]]
